apiVersion: v1
kind: Service
metadata:
  name: {{ include "calendar-reminder.fullname" . }}
  labels:
    {{- include "calendar-reminder.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "calendar-reminder.webSelectorLabels" . | nindent 4 }}
